remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Andres Lancheros Díaz
submodulo: Nuevas tecnologias
periodo: 2023-2
url_foto:https://firebasestorage.googleapis.com/v0/b/new-tecnologies.appspot.com/o/jaime.jpeg?alt=media&token=ae70d125-28c4-44ab-ba7e-645b2078a7cd&_gl=1*13ecpe9*_ga*NDQ5OTkxMTgwLjE2ODE3ODEyNTk.*_ga_CW55HF8NVT*MTY5NjUyMTYwOC43LjEuMTY5NjUyMjg0OS42MC4wLjA.

